---
- name: "MediaWiki db configuration"
  hosts: db
  gather_facts: no
  tags: [ "mariadb", "mysql" ]
  roles:
    - role: "mediawiki/confdb"

- name: "MediaWiki apache configuration"
  hosts: apache
  gather_facts: no
  tags: "apache"
  roles:
    - role: "mediawiki/confapache"

- name: "MediaWiki default content"
  hosts: apache
  gather_facts: no
  tags: "content"
  roles:
    - role: "mediawiki/wikicontent"